server:
    port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: pguser
    password: S3cret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect